-- =========================================================
-- DAY 77
-- E-COMMERCE POSTGRESQL DATABASE
-- 30 SQL CHALLENGES
-- =========================================================


-- =========================================================
-- DATABASE & SCHEMA
-- =========================================================

-- 1. Create the ecommerce database.
--
-- CREATE DATABASE ecommerce;


-- 2. Create the users table.
--
-- Requirements:
-- id PRIMARY KEY
-- name NOT NULL
-- email NOT NULL UNIQUE
-- created_at DEFAULT CURRENT_TIMESTAMP


-- 3. Create the categories table.
--
-- Requirements:
-- id PRIMARY KEY
-- name NOT NULL UNIQUE
-- description
-- created_at


-- 4. Create the products table.
--
-- Requirements:
-- category_id FOREIGN KEY
-- name NOT NULL
-- price >= 0
-- stock >= 0
-- is_active BOOLEAN


-- 5. Create the orders table.
--
-- Requirements:
-- user_id FOREIGN KEY
-- status NOT NULL
-- total_amount >= 0


-- 6. Create the order_items table.
--
-- Requirements:
-- order_id FOREIGN KEY
-- product_id FOREIGN KEY
-- quantity > 0
-- price >= 0


-- 7. Add primary keys to all tables.


-- 8. Add foreign keys:
--
-- products.category_id → categories.id
-- orders.user_id → users.id
-- order_items.order_id → orders.id
-- order_items.product_id → products.id


-- 9. Add unique constraints:
--
-- users.email
-- categories.name


-- 10. Add CHECK constraints:
--
-- products.price >= 0
-- products.stock >= 0
-- orders.total_amount >= 0
-- order_items.quantity > 0
-- order_items.price >= 0



-- =========================================================
-- INSERT
-- =========================================================

-- 11. Insert 20 users.


-- 12. Insert 5 categories.


-- 13. Insert 30 products.


-- 14. Insert 15 orders.


-- 15. Insert 40 order items.



-- =========================================================
-- SELECT
-- =========================================================

-- 16. Get all users.


-- 17. Get all products.


-- 18. Get all categories.


-- 19. Get products above ₹1,000.


-- 20. Get products below ₹500.



-- =========================================================
-- FILTERING
-- =========================================================

-- 21. Find products with zero stock.


-- 22. Find products between ₹500 and ₹2,000.


-- 23. Find products belonging to categories
--     1, 3 and 5.


-- 24. Find users whose name contains "a".


-- 25. Find products whose name contains "phone".



-- =========================================================
-- SORTING
-- =========================================================

-- 26. Find the top 5 most expensive products.


-- 27. Find the top 5 cheapest products.


-- 28. Sort users alphabetically.


-- 29. Sort products by stock.


-- 30. Return only the first 10 products.



-- =========================================================
-- BONUS CHALLENGES
-- =========================================================

-- BONUS 1
-- Find the average product price.


-- BONUS 2
-- Find the highest product price.


-- BONUS 3
-- Find the lowest product price.


-- BONUS 4
-- Count total products.


-- BONUS 5
-- Count active products.


-- BONUS 6
-- Count inactive products.


-- BONUS 7
-- Find products with stock between 10 and 50.


-- BONUS 8
-- Find users whose name starts with 'A'.


-- BONUS 9
-- Find products whose name ends with 'er'.


-- BONUS 10
-- Find all orders belonging to user_id = 1.


-- BONUS 11
-- Find all delivered orders.


-- BONUS 12
-- Find all cancelled orders.


-- BONUS 13
-- Find orders above ₹5,000.


-- BONUS 14
-- Find products grouped by category.


-- BONUS 15
-- Find the number of products in each category.


-- BONUS 16
-- Find the average product price for each category.


-- BONUS 17
-- Find the most expensive product in each category.


-- BONUS 18
-- Find the cheapest product in each category.


-- BONUS 19
-- Find the total quantity sold for each product.


-- BONUS 20
-- Find the total revenue generated by each product.