-- =========================================================
-- DAY 78
-- PRODUCTION E-COMMERCE SCHEMA V2
-- CHALLENGES
-- =========================================================


-- =========================================================
-- SCHEMA DESIGN
-- =========================================================

-- 1. Explain why users.email should be UNIQUE.


-- 2. Explain why password_hash should never be nullable.


-- 3. Explain why addresses should reference users
--    using a FOREIGN KEY.


-- 4. Explain why products.category_id should be
--    a FOREIGN KEY.


-- 5. Explain why products.sku should be UNIQUE.


-- 6. Explain why product_variants.sku should be UNIQUE.


-- 7. Explain the purpose of:
--
-- UNIQUE(product_id, size, color)


-- 8. Why can product_variants.price be different
--    from products.price?


-- 9. Why should order_items.unit_price be stored
--    separately from products.price?


-- 10. Why should order_items.quantity be > 0?



-- =========================================================
-- CONSTRAINT CHALLENGES
-- =========================================================

-- 11. Create a product with a negative price.
--
-- What happens?


-- 12. Create a product with negative stock.
--
-- What happens?


-- 13. Insert a duplicate user email.
--
-- What happens?


-- 14. Insert a duplicate product SKU.
--
-- What happens?


-- 15. Insert a duplicate variant:
--
-- Same product
-- Same size
-- Same color
--
-- What happens?


-- 16. Insert an order with negative tax.


-- 17. Insert an order with negative shipping fee.


-- 18. Insert an order with negative discount.


-- 19. Insert an order item with quantity = 0.


-- 20. Insert a payment with negative amount.



-- =========================================================
-- RELATIONSHIP CHALLENGES
-- =========================================================

-- 21. Find all addresses belonging to user_id = 1.


-- 22. Find all products belonging to Electronics.


-- 23. Find all variants of the Classic T-Shirt.


-- 24. Find all orders placed by Rahul.


-- 25. Find all products purchased by Rahul.


-- 26. Find all payments made by Rahul.


-- 27. Find users who have never placed an order.


-- 28. Find products that have no variants.


-- 29. Find users who have more than one address.


-- 30. Find orders that do not have a payment record.



-- =========================================================
-- PRODUCTION THINKING
-- =========================================================

-- 31. Should payment.transaction_id be UNIQUE?
--     Explain your decision.


-- 32. Should payment.transaction_id be NOT NULL?
--     Think about COD and pending payments.


-- 33. Should payment.order_id be UNIQUE?
--     What changes if an order can have multiple
--     payment attempts?


-- 34. Should product SKU be generated by PostgreSQL
--     or by the application?


-- 35. Should order_items.product_id use ON DELETE CASCADE?
--     Explain why or why not.


-- 36. Should addresses use ON DELETE CASCADE?
--     Explain.


-- 37. Should products be physically deleted from
--     production systems?


-- 38. Why is is_active useful for products?


-- 39. Why should financial amounts use NUMERIC
--     instead of FLOAT?


-- 40. What happens if the current product price changes
--     after an order has been completed?



-- =========================================================
-- ADVANCED
-- =========================================================

-- 41. Find the top 5 customers by total spending.


-- 42. Find the top 5 products by revenue.


-- 43. Find the category generating the highest revenue.


-- 44. Find products whose stock is below 10.


-- 45. Find the most expensive product variant.


-- 46. Find the number of variants per product.


-- 47. Find the average order value.


-- 48. Find total revenue from paid payments.


-- 49. Find cancelled orders and their payment status.


-- 50. Find users who have both:
--     multiple addresses
--     and multiple orders.